# Name and URL of company, leave this to default settings when demoing
companyName: "Vamting"
companyUrl: "https://vamting.com"

# Enable if the webpanel is behind a proxy
behind_proxy: True

# Website language (this setting is global)
language: "en_int"

# webpanel ip and port
webpanelIp: 0.0.0.0
webpanelPort: 2050

stagerSubDomain: "Neushoorn"

# !!! ---------- !!! ---------- !!! ----------- !!! ----------- !!! ----------- !!! ----------- !!!
#
#Below are developer options that should NEVER be changed in a production enviroment
#
# !!! ---------- !!! ---------- !!! ----------- !!! ----------- !!! ----------- !!! ----------- !!!

# Enable/disable developer mode
devmode: True

# When set to FALSE It will delete ALL previously made logs.
# Don't use this unless you really know what you're doing.
# Support will not be provided without these logs.
dontWipeLogs: True

